### ISSUE TITLE
PWA docs

### ISSUE THREAD

**Issue by sxzz** [sxzz/unplugin-vue-macros#110]

**Comment by sxzz** [comment]
@hydrati Would you like to contribute to this when you're free? If yes, I will be very appreciated. 😆

**Comment by hydrati** [comment]
> @hydrati Would you like to contribute to this when you're free? If yes, I will be very appreciated. 😆

I have lessons from Mon to Sat, so I try to do. :)

**Comment by hydrati** [comment]
> @hydrati Would you like to contribute to this when you're free? If yes, I will be very appreciated. 😆

See #114
