### ISSUE TITLE
`withDefaults` breaks the `defineModel` macro

### ISSUE THREAD

**Issue by ldiebold** [sxzz/unplugin-vue-macros#133]
### Describe the bug

`defineModel` works everywhere except when using `withDefaults`

```ts
const { form } = defineModel<{
  form: { name: string }
}>()

interface Props {
  color: string
}

withDefaults(defineProps<Props>(), {
  color: 'blue'
})
```

I'm guessing the compiler is not noticing `withDefaults` and therefore, not finding `defineProps` within.

Here's a reproduction:
https://stackblitz.com/edit/vitejs-vite-b7hjq1?file=src/components/CreatePost.vue

And here is more of the error:
```
[plugin:vite:vue] [@vue/compiler-sfc] duplicate defineProps() call

/home/projects/vitejs-vite-b7hjq1/src/components/CreatePost.vue
11 |  }
12 |  
13 |  withDefaults(defineProps<Props>(), {
   |               ^^^^^^^^^^^^^^^^^^^^
14 |    color: 'blue',
15 |  });
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-b7hjq1?file=src/components/CreatePost.vue

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Thanks! Released in #130
