### ISSUE TITLE
unplugin-vue-define-options  report bug use in rollup 

### ISSUE THREAD

**Issue by danielmlc** [sxzz/unplugin-vue-macros#134]
### Describe the bug

!] (plugin rpt2) Error: src/components/panel/panel.vue?vue&type=script&setup=true&lang.ts:35:46 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ props: { showHeader: { type: BooleanConstructor; required: boolean; default: boolean; }; title: { type: StringConstructor; required: boolean; default: string; }; contentStyle: { ...; }; border: { ...; }; shadow: { ...; }; }; ... 57 more ...; style?: unknown; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{}, unknown, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, string[], string, Readonly<ExtractPropTypes<{}>> & { ...; }, {}>'.
      Type '{ props: { showHeader: { type: BooleanConstructor; required: boolean; default: boolean; }; title: { type: StringConstructor; required: boolean; default: string; }; contentStyle: { ...; }; border: { ...; }; shadow: { ...; }; }; ... 57 more ...; style?: unknown; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{}>> & { [x: `on${Capitalize<string>}`]: ((...args: any[]) => any) | undefined; }, unknown, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, string[], string, {}>'.
        Types of property 'emits' are incompatible.
          Type 'ThisType<void> | (string[] & ThisType<void>) | undefined' is not assignable to type '(string[] & ThisType<void>) | undefined'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
              Type 'ThisType<void>' is missing the following properties from type 'string[]': length, pop, push, concat, and 29 more.

 35 export default /*#__PURE__*/_defineComponent({
                                                 ~
 36   ...__default__,
    ~~~~~~~~~~~~~~~~~

### Reproduction

"pinia": "^2.0.17",

### System Info

```Shell
"rollup": "^2.60.0",
"unplugin-vue-define-options": "^0.12.3",
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Please use `vue-tsc` to emit dts, instead of Rollup.
