### ISSUE TITLE
Storybook Support

### ISSUE THREAD

**Issue by samydoesit** [sxzz/unplugin-vue-macros#145]
### Describe the bug

I am trying to use this with Storybook but i am getting erros like these:
```bash
ERR! TypeError: (0 , vite_1.default) is not a function
ERR!     at Object.viteFinal (/home/projects/vitejs-vite-pfyr4e/.storybook/main.ts:21:16)
ERR!     at eval (/home/projects/vitejs-vite-pfyr4e/node_modules/@storybook/core-common/dist/cjs/presets.js:294:28)
ERR!  TypeError: (0 , vite_1.default) is not a function
ERR!     at Object.viteFinal (/home/projects/vitejs-vite-pfyr4e/.storybook/main.ts:21:16)
ERR!     at eval (/home/projects/vitejs-vite-pfyr4e/node_modules/@storybook/core-common/dist/cjs/presets.js:294:28)
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pfyr4e?file=.storybook/main.ts

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.60 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.n/bin/node
    npm: 8.19.2 - ~/.n/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.4
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://github.com/sxzz/vue-macros-storybook

Make sure it's the first plugin `config.plugins.unshift(VueMacros())`, and `@storybook/builder-vite` will inject the vite-vue plugin, so you needn't add it to vue macros.

Also, it's really bad for the support of Storybook with Vue and ESM.
There are lots of known bugs. 😅 So, there's no plan to support it officially and I don't promise it will work in the future.

**Comment by sxzz** [comment]
I strongly recommend using [Histoire](https://histoire.dev/) instead.
