### ISSUE TITLE
`betterDefine` feature does not work when `defineOptions` macro used in same component

### ISSUE THREAD

**Issue by geewizz246** [sxzz/unplugin-vue-macros#166]
### Describe the bug

I'm trying to use the `betterDefine` feature in addition to disabling the `inheritAttrs` option on one of my components. However, `betterDefine` does not work when `defineOptions` is used in the same component. The standard way of disabling the `inheritAttrs` option [provided by vue](https://vuejs.org/guide/components/attrs.html#disabling-attribute-inheritance) does not work either.

```vue
<script setup lang="ts">
import type { MyInputProps } from './types';

defineOptions({ inheritAttrs: false });

defineProps<MyInputProps>();
</script>
```

This is the error I am getting in the console:

```
[vite] Internal server error: unplugin-vue-define-options Error: [@vue/compiler-sfc] type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.

/home/projects/vitejs-vite-5wz2cq/src/components/MyInput/MyInput.vue
8  |  defineOptions({ inheritAttrs: false });
9  |  
10 |  defineProps<MyInputProps>();
   |              ^^^^^^^^^^^^
11 |  </script>
12 |  
  Plugin: unplugin-vue-define-options
```

I tried disabling `defineOptions` in the vite config but it makes no difference.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-5wz2cq?file=src/components/MyInput/MyInput.vue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.97 GB / 15.88 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by coderwyd** [comment]
I had the same problem
![image](https://user-images.githubusercontent.com/53386850/210969839-a4e60818-64f5-447d-87dc-57d5e07d27dd.png)
![image](https://user-images.githubusercontent.com/53386850/210969936-e6122558-bb06-45ab-a45a-61c1431a4792.png)

**Comment by coderwyd** [comment]
> Fixed in `unplugin-vue-macros@1.3.0`

Can't `unplugin-vue-Definition-options` be used on its own?

**Comment by sxzz** [comment]
@coderwyd Sure! It does, also fixed in `unplugin-vue-define-options@1.1.2`

**Comment by coderwyd** [comment]
> @coderwyd Sure! It does, also fixed in `unplugin-vue-define-options@1.1.2`
I upgraded it to v1.1.2, but it still didn't work on my project.
![image](https://user-images.githubusercontent.com/53386850/211261157-0d0f6da8-5820-4290-9ae4-7c2ed8ad16c6.png)
![image](https://user-images.githubusercontent.com/53386850/211261224-f33399b7-a842-4d24-b57f-3cee4b4f8f27.png)

**Comment by sxzz** [comment]
@coderwyd There's only one feature `defineOptions` in `unplugin-vue-define-options`. That means `unplugin-vue-define-options` don't provide the `betterDefine` feature, and you cannot use it.

You can read docs for more information about `betterDefine`. https://vue-macros.sxzz.moe/features/better-define.html

**Comment by coderwyd** [comment]
> @coderwyd There is only one feature `defineOptions` in `unplugin-vue-define-options`. That means `unplugin-vue-define-options` don't provide the `betterDefine` feature, and you cannot use it.
> 
> You can read docs for more information about `betterDefine`. https://vue-macros.sxzz.moe/features/better-define.html

Thank you, I know what to do.
