### ISSUE TITLE
添加 eslint 支持？目前只能通过 "no-undef": "off" ，但是这样 eslint 失去了意义

### ISSUE THREAD

**Issue by kaivanwong** [sxzz/unplugin-vue-macros#171]
### Describe the bug

`'defineOptions' is not defined.eslint[no-undef](https://eslint.org/docs/rules/no-undef)`

### Reproduction

defineOptions({   name: 'SystemRole', });

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 752.65 MB / 15.83 GB
  Binaries:
    Node: 14.18.1 - D:\Software\nvm-node\node.EXE
    Yarn: 1.22.19 - D:\Software\nvm-node\yarn.CMD
    npm: 6.14.15 - D:\Software\nvm-node\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
You can add the `globals` option into ESLint config if you're using plain JavaScript. For TypeScript project, disabling `no-undef` is acceptable, since TypeScript compiler will check the variable if it exists.

```jsonc
// .eslintrc
{
    "globals": {
        "defineOptions": "readonly"
    }
}
```

**Comment by kaivanwong** [comment]
非常感谢，我现在使用 `globals` 解决了 eslint校验的问题。我有一个想法，对于 `setup` 语法糖中定义 组件 的名称，能否实现通过 `<script lang="ts" setup name="aaa">` 这种形式实现给 组件 添加名称？

**Comment by kaivanwong** [comment]
> You can add the `globals` option into ESLint config if you're using plain JavaScript. For TypeScript project, disabling `no-undef` is acceptable, since TypeScript compiler will check the variable if it exists.
> 
> [Refer to ESLint docs](https://eslint.org/docs/latest/user-guide/configuring/language-options#using-configuration-files-1)
> 
> ```js
> // .eslintrc
> {
>     "globals": {
>         "defineOptions": "readonly"
>     }
> }
> ```
> 
> See also [example](https://github.com/sxzz/eslint-config/blob/main/packages/vue/index.js#L39)

非常感谢，我现在使用 `globals` 解决了 `eslint` 校验的问题。我有一个想法，对于 `setup` 语法糖中定义 组件 的名称，能否实现通过 `<script lang="ts" setup name="aaa">` 这种形式实现给 组件 添加名称？

**Comment by sxzz** [comment]
不考虑此方案。更多讨论在 [RFC](https://github.com/vuejs/rfcs/discussions/430#discussioncomment-2201172) 中。

**Comment by kaivanwong** [comment]
> 不考虑此方案。更多讨论在 [RFC](https://github.com/vuejs/rfcs/discussions/430#discussioncomment-2201172) 中。

ok，感谢☺️
