### ISSUE TITLE
betterDefine 能否支持推导外部库的Props

### ISSUE THREAD

**Issue by PopperLi** [sxzz/unplugin-vue-macros#175]
### Clear and concise description of the problem

刚开始我使用`interface`继承了`ElTableProps`但编译产物没有把它带入props中。后来我尝试直接在`.vue`中使用`defineProps`定义，但会直接报错。

![image](https://user-images.githubusercontent.com/31717528/206398783-4b68125c-0ee4-4eb5-9eb3-c94ca83b0f19.png)

### Suggested solution

希望能推导依赖类型

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Element Plus 是使用 Object 运行时定义 props 和 emits 的。所以没有办法分析出 TS 的类型。

可以直接导入小写的 `buttonProps` 继承
```ts
import { buttonProps } from 'element-plus'
const myButtonProps = {
  ...buttonProps,
  // ... your props
}
```
