### ISSUE TITLE
和vue/multi-word-component-names选项之间怎么融合?

### ISSUE THREAD

**Issue by qqfei1858** [sxzz/unplugin-vue-macros#176]
### Describe the bug

和vue/multi-word-component-names选项之间怎么融合?
项目中vue/multi-word-component-names是打开的

### Reproduction

无

### System Info

```Shell
无
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
可以自行选择在 ESLint 关掉该规则
https://eslint.vuejs.org/rules/multi-word-component-names.html#options

**Comment by LadenxxxxD** [comment]
把这个eslint规则关闭了，我也就不需要到处找插件了

**Comment by CrabSAMA** [comment]
> 把这个eslint规则关闭了，我也就不需要到处找插件了

https://github.com/vuejs/eslint-plugin-vue/commit/a9bd24c8b5eb4e1a9d0f1d714b80393d235dc8db
eslint-plugin-vue version > v9.13.0 work great
