### ISSUE TITLE
Missing documentation to configure the plugin for vue 2.7

### ISSUE THREAD

**Issue by rbecheras** [sxzz/unplugin-vue-macros#180]
### Describe the bug

The doc says that vue2.7 is supported by the plugin 

And the doc explain how to [configure it for webpack](https://vue-macros.sxzz.moe/guide/bundler-integration.html#installation)

```js
// webpack.config.js
module.exports = {
  /* ... */
  plugins: [
    require('unplugin-vue-macros/webpack')({
      plugins: {
        vue: require('unplugin-vue/webpack')(),
        // vueJsx: VueJsx(), // if needed
      },
    }),
  ],
}
```

But `unplugin-vue` supports only vue3.

So I guess that there is a lack of documentation, or the plugin doesn't support vue 2.7?

### Reproduction

vue2.7 + webpack5 + vue-cli

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 155.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chrome: 108.0.5359.98
    Firefox: 103.0.2
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Documentation is updated https://github.com/sxzz/unplugin-vue-macros/commit/d682e6447c44f02007a721fc24dabf4b0aacd730

You can also refer to demos below




- [Vite + Vue 3](https://github.com/sxzz/unplugin-vue-macros/tree/main/playground/vue3)
- [Vite + Vue 2](https://github.com/sxzz/unplugin-vue-macros/tree/main/playground/vue2)
- [Nuxt 3 + Vue 3](https://github.com/vue-macros/nuxt)
- [Vue CLI + Vue 2](https://github.com/vue-macros/vue2-vue-cli)

**Comment by CapitaineToinon** [comment]
Can we also have an example for a Nuxt 2 app?
