### ISSUE TITLE
Conflicting peer dependency when using with Vue 2.7

### ISSUE THREAD

**Issue by craigrileyuk** [sxzz/unplugin-vue-macros#192]
### Describe the bug

The package has `@vue-macros/define-props` as a direct dependency, which in turn lists `"vue": "^3.2.25"` as a peerDependency.

This results in a conflict warning when using the package within a Vue 2.7 application.

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
`$defineProps` now supported Vue 2.
