### ISSUE TITLE
jsx  + reactivity transform got error "This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript""

### ISSUE THREAD

**Issue by TonyYanOnFire** [sxzz/unplugin-vue-macros#198]
### Describe the bug

Using jsx along side reactivity transform in a SFC, got this error:

```
ERROR in ./src/App.vue
Module Error (from ./node_modules/unplugin/dist/webpack/loaders/transform.js):
unplugin-reactivity-transform-vue2 SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (14:11)
```

Main codes:
```
<script>
import Vue from 'vue'

Vue.component("my-h", {
  name: "MyH",
  props: {
    level: {
      type: Number,
      required: true
    }
  },
  render(h) {
    const Tag = `h${this.level}`
    return <Tag>{this.$slots.default}</Tag>;
  }
});

export default {
  setup () {
    const randomLevel = $ref(Math.ceil(Math.random() * 6))

    return {
      ...$$({
        randomLevel
      })
    }
  }
}
</script>

<template>
  <div>
    <my-h :level="randomLevel">I'm random</my-h>
  </div>
</template>
```

Dependencies version:
webpack4
vue2.7
jsx enable by @vue/babel-preset-jsx

### Reproduction

https://github.com/TonyYanOnFire/jsx-reactivity-transform-error-reproduction

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 4.32 GB / 15.89 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.17763.1.0)
    Internet Explorer: 11.0.17763.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed in `unplugin-vue-macros@1.3.0`
