### ISSUE TITLE
After using the plugin VueMacros, the packaging time slows down a lot

### ISSUE THREAD

**Issue by wydingez** [sxzz/unplugin-vue-macros#204]
### Describe the bug

```js
plugins: {
    VueMacros()
}
```

The betterDefine of the VueMacros plug-in is introduced in the project to solve the problem that the ts type cannot be introduced in the vue file, but the packaging time before and after the introduction has slowed down a lot. What are the possible reasons?

<img width="829" alt="image" src="https://user-images.githubusercontent.com/26266181/211265217-3116aaf7-8743-482c-9541-8af6cc60a3f0.png">

### Reproduction

N/A

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 455.77 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 13.1.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Oh it looks really bad. Could you please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) that I can investigate it more clearly. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Comment by wydingez** [comment]
minimal reproduction: https://github.com/wydingez/vue-macros-build-slow

<img width="815" alt="image" src="https://user-images.githubusercontent.com/26266181/211270762-de605f40-d4a9-433c-b9af-87e94947da3d.png">

**Comment by sxzz** [comment]
Could you please try `unplugin-vue-macros@1.3.2` and test it again?

**Comment by wydingez** [comment]
> Could you please try `unplugin-vue-macros@1.3.2` and test it again?

ok，upgrade to `unplugin-vue-macros@1.3.2`, the problem is solved, thanks
