### ISSUE TITLE
$ can only be used as the initializer of a variable declaration

### ISSUE THREAD

**Issue by tjx666** [sxzz/unplugin-vue-macros#209]
### Describe the bug

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/212358098-95d5500f-2783-400c-ab31-7565788a3ba0.png">

reproduce:

- `git clone git@github.com:tjx666/vite-issue-reproduce.git`
- `pnpm install`
- `pnpm build`
- `pnpm dev`

### Reproduction

https://github.com/tjx666/vite-issue-reproduce

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 83.37 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/4074_1673624031027/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/4074_1673624031027/bin/yarn
    npm: 9.3.0 - ~/Library/Caches/fnm_multishells/4074_1673624031027/bin/npm
    pnpm: 7.24.3
  Browsers:
    Chrome: 109.0.5414.87
    Firefox Developer Edition: 104.0
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
It's the bug of Vue core  https://github.com/vuejs/core/pull/7505. We have to wait until the PR is merged and released.
And please exclude the 3rd party file, which only your app files will be included.
```ts
        VueMacros({
            plugins: {
                vue: vitePluginVue2(),
                vueJsx: vitePluginVue2Jsx(),
            },
            betterDefine: true,
            reactivityTransformVue2: {
                exclude: [/node_modules/, /zepto\.js/]
            }
        }),
```

**Comment by sxzz** [comment]
Fixed in Vue Macros version.
