### ISSUE TITLE
Webpack / Vue CLI: `defineOptions is not defined` (production mode)

### ISSUE THREAD

**Issue by ShaneLee-9** [sxzz/unplugin-vue-macros#23]
![image](https://user-images.githubusercontent.com/30720287/169256446-53d2d48f-d219-4896-ab04-14d9af6c75e9.png)

![image](https://user-images.githubusercontent.com/30720287/169256632-8c351baa-4027-4ad3-a347-54e3a3ff68da.png)

dependencies：
"vue": "^3.2.13",
"unplugin-vue-define-options": "^0.6.1",
”webpack": "5.70.0"

`vue.config.js` config：
![image](https://user-images.githubusercontent.com/30720287/169257040-3a161925-fea5-4bc1-8ff2-22b8513c5f84.png)

**Comment by sxzz** [comment]
Please provide a reproduction repo.

**Comment by ShaneLee-9** [comment]
This is the project repo: https://github.com/ShaneLee-9/vue-define-options-demo
This is the production: https://shanelee-9.github.io/vue-define-options-demo/

**Comment by wangshuai0** [comment]
同样遇到，解决了吗

**Comment by sxzz** [comment]
用于webpack下暂时有点问题

**Comment by giserman001** [comment]
> 用于webpack下暂时有点问题

如何在typescript下定义d.ts声明

**Comment by sxzz** [comment]
@ShaneLee-9 @wangshuai0 似乎是与 babel 一起用的时候会出问题，尝试去掉 babel 试试

**Comment by sxzz** [comment]
@giserman001 https://github.com/sxzz/unplugin-vue-define-options/issues/13#issuecomment-1066300557

**Comment by sxzz** [comment]
暂无解决方法，等上游修复

**Comment by HOLYYUN** [comment]
> 暂无解决方法，等上游修复
Copy that!

**Comment by funyaliga** [comment]
我用vite也是生产环境not defined，但dev环境没问题

**Comment by zjluse** [comment]
发现把node_modules删掉，重新install，马上再build就不会有问题， 但是偶尔关机或者重启编辑器可能就会再次报错！

**Comment by sxzz** [comment]
@ckvv 请提供最小复现。

**Comment by sxzz** [comment]
@ckvv 没问题的，因为使用了别名

```
  "typesVersions": {
    "*": {
      "*": [
        "./dist/*",
        "./*"
      ]
    }
  },
```

**Comment by iEuJen** [comment]
> "0.8.0" 在 vite中存在相同问题， 回退到"0.7.3"版本正常，

是的，我用最新版[0.11.2]也出现报错的情况，在回退到0.7.3之后便正常了。

vscode报错信息
```
any
找不到名称“defineOptions”。ts(2304)
没有可用的快速修复
```

下面是我的项目依赖：
```json
{
 "dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-components": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-h5": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3050320220727002",
    "pinia": "^2.0.20",
    "vue": "^3.2.37",
    "vue-i18n": "^9.1.9",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.0.7",
    "@dcloudio/uni-automator": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-3050320220727002",
    "@dcloudio/uni-stacktracey": "3.0.0-alpha-3050320220727002",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3050320220727002",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^7.0.0",
    "postcss-html": "^1.3.0",
    "postcss-scss": "^4.0.3",
    "sass": "^1.54.5",
    "stylelint": "^14.5.3",
    "stylelint-config-html": "^1.0.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-standard": "^25.0.0",
    "stylelint-order": "^5.0.0",
    "stylelint-scss": "^4.1.0",
    "typescript": "^4.7.4",
    "unplugin-vue-define-options": "^0.11.2",
    "vite": "^2.9.14"
  }
}
```

**Comment by sxzz** [comment]
最新版需要手动配置

``
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": ["unplugin-vue-define-options/macros-global" /* ... */]
  }
}
```

**Comment by qinyang912** [comment]
I have a minimal webpack config:
```js
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const defineOptions = require('unplugin-vue-define-options/webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  mode: 'development',
  entry: './test.vue',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
          },
        ],
      },
    ],
  },
  plugins: [new VueLoaderPlugin(), defineOptions()],
  devtool: false,
};
```
the configuration above can not work,  unless I add a loader
```js
{
  loader: 'unplugin/dist/webpack/loaders/transform?unpluginName=unplugin-vue-define-options',
}
```

the full configuration is:
```js
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const defineOptions = require('unplugin-vue-define-options/webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  mode: 'development',
  entry: './test.vue',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
          },
          {
            loader:
              'unplugin/dist/webpack/loaders/transform?unpluginName=unplugin-vue-define-options',
          },
        ],
      },
    ],
  },
  plugins: [new VueLoaderPlugin(), defineOptions()],
  devtool: false,
};
```

I have create a StackBlitz demo, the link: https://stackblitz.com/edit/node-fu77mv?file=package.json,index.js,test.vue,webpack.config.js,dist%2Fmain.js

you can run `npm run build` in the terminal to see the different in the  output file `dist/main.js`, the screenshot:

with this loader:
![image](https://user-images.githubusercontent.com/5723181/196897328-4b67f4a4-bf2a-4650-a0a2-0920666fe000.png)

without this loader:
![image](https://user-images.githubusercontent.com/5723181/196897386-2c6b06fc-4bbe-4b31-bc5f-ecc0837daaf9.png)

**Comment by sxzz** [comment]
@qinyang912 Thanks for your feedback! For Vue 2 (Vue loader 15) + Webpack, an additional option is required.
```js
  plugins: [
    defineOptions({
      include: [/\.vue$/, /\.vue\?vue/],
    }),
    new VueLoaderPlugin(),
  ],
```

I will add it to the documentation later.

**Comment by qq619433305** [comment]
请问目前有解决办法了么。同为webpack5报错，显示 defineOptions is not defined

**Comment by Nstd** [comment]
> 请问目前有解决办法了么。同为webpack5报错，显示 defineOptions is not defined

@qq619433305 

vue 3
webpack 5
非 TS
使用这个可以：https://github.com/sxzz/unplugin-vue-macros/issues/23#issuecomment-1285433093
``` js
   defineOptions({
      include: [/\.vue$/, /\.vue\?vue/],
    })
```

**Comment by ShaneLee-9** [comment]
> 

使用这个配置尝试，打包后还是会报一样的错

**Comment by ShaneLee-9** [comment]
> > 请问目前有解决办法了么。同为webpack5报错，显示 defineOptions is not defined
> 
> @qq619433305
> 
> vue 3 webpack 5 非 TS 使用这个可以：[#23 (comment)](https://github.com/sxzz/unplugin-vue-macros/issues/23#issuecomment-1285433093)
> 
> ```js
>    defineOptions({
>       include: [/\.vue$/, /\.vue\?vue/],
>     })
> ```

@Nstd 
使用这个配置尝试，打包后还是会报一样的错

**Comment by Nstd** [comment]
@ShaneLee-9 你用的啥环境（版本）？配置文件看看

**Comment by ShaneLee-9** [comment]
@Nstd 这是仓库地址：https://github.com/ShaneLee-9/vue-options-plugin-test
用的 `vue-cli v5` 搭建的 `vue3` 模板，只修改了 `vue.config.js` 和 `HellowWorld.vue` 文件。开发环境没问题，打包后报错，下面是运行的截图：

### 开发环境
![开发环境](https://user-images.githubusercontent.com/30720287/202609541-accde391-9222-46cd-955c-e13ef0418cd4.png)

### 打包后
![生产环境](https://user-images.githubusercontent.com/30720287/202609582-775a7fd4-808e-4482-86b4-f3f782142b1b.png)

**Comment by ShaneLee-9** [comment]
@Nstd 对了，`node` 版本是 `14.19.2`，`npm` 是 `9.1.1`，系统是 Win10 22H2

**Comment by Nstd** [comment]
> @Nstd 对了，`node` 版本是 `14.19.2`，`npm` 是 `9.1.1`，系统是 Win10 22H2

@ShaneLee-9 我用你的代码试了两个版本（我本地的）都没报错，不会不是 `npm` 版本不匹配？
``` shell
node 14.15.0   npm 6.14.8
node 16.10.0   npm 7.24.0
```
![image](https://user-images.githubusercontent.com/3004225/202978866-14867aa0-e3b1-43cd-b9ff-07f5e59e46e4.png)

**Comment by Nstd** [comment]
> @Nstd 对了，`node` 版本是 `14.19.2`，`npm` 是 `9.1.1`，系统是 Win10 22H2

@ShaneLee-9 需要再加个一个配置：
https://github.com/sxzz/unplugin-vue-macros/issues/23#issuecomment-1170283222

**Comment by ShaneLee-9** [comment]
@Nstd 有用！

**Comment by zhoutengshen** [comment]
我也遇到了，咋整

**Comment by CyanSalt** [comment]
> You can set `parallel: false` in vue.config.js to disable thread-loader.
> 
> Related： [vuejs/vue-cli#2785 (comment)](https://github.com/vuejs/vue-cli/issues/2785#issuecomment-432106435) [webpack-contrib/thread-loader#27](https://github.com/webpack-contrib/thread-loader/issues/27)

You can use [`parallelize-webpack-unplugin`](https://github.com/CyanSalt/parallelize-webpack-unplugin) if you have tried this method and it works. It partially simplifies the parameters that unplugin depends on to allow the plugin to support running with `thread-loader`, so that you can enjoy the benefits of concurrent compilation at the same time.
