### ISSUE TITLE
Deprecate macros relying on Reactivity Transform

### ISSUE THREAD

**Issue by nathanchase** [sxzz/unplugin-vue-macros#246]
### Clear and concise description of the problem

Namely defineProps: https://vue-macros.sxzz.moe/macros/define-props.html

See https://github.com/vuejs/rfcs/discussions/369#discussioncomment-4779240 for more.

### Suggested solution

Or at least update docs to reflect that it's no longer part of Vue 3 core.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Props destructuring won’t be removed. It will be separated and moved to another new proposal. We (Vue team) will discuss it in the next days.

**Comment by sxzz** [comment]
https://github.com/vuejs/rfcs/discussions/369#discussioncomment-5059028

**Comment by sxzz** [comment]
Reactivity Transform is moved to Vue Macros, and we'll maintain it further.
