### ISSUE TITLE
仓库中vue3+vite的代码示例报错

### ISSUE THREAD

**Issue by AC-0308** [sxzz/unplugin-vue-macros#251]
### Describe the bug

本仓库中vue3+vite的代码示例在IDE中报红(已经正常pnpm install)。
![fef22db6bef907bcb69a0cfafcaf25c](https://user-images.githubusercontent.com/49855945/215318840-d454a4ca-a93d-4ab0-b8f7-2c1bdbb7cea3.png)

### Reproduction

no need

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 3.79 GB / 15.91 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.70)    
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
fixed

**Comment by zynth17** [comment]
got the same issue with `unplugin-vue-define-options 1.2.0`
<img width="698" alt="image" src="https://user-images.githubusercontent.com/45350572/215401036-80d3a705-5f73-4773-8ff0-11b686b79c2e.png">

**Comment by AC-0308** [comment]
经定位该问题是从1.7.0版本开始的，之前版本正常
