### ISSUE TITLE
tsconfig.**.json配置文件问题

### ISSUE THREAD

**Issue by AliceLanniste** [sxzz/unplugin-vue-macros#256]
**Describe the bug**
我已经`pnpm install` 依赖
`tsconfig.lib.json` 出现如下错误提示，没有`customConditions` 这个属性。
![屏幕截图 2023-01-31 094443](https://user-images.githubusercontent.com/17617116/215638405-c5ae546c-a4f0-4a37-8d9d-ae66cfd97a67.png)
`tsconfig.fixture.json`出现如下问题
![image](https://user-images.githubusercontent.com/17617116/215638572-866af98c-8e2e-4d20-ab2c-e6152bb166ae.png)
我根据提示修改`tsconfig.lib.json`和`tsconfig.fixture.json`
tsconfig.lib.json：
![屏幕截图 2023-01-31 095804](https://user-images.githubusercontent.com/17617116/215640313-f6b3bc16-ad41-4b63-ab92-e1a90a26d036.png)

tsconfig.fixture.json：
![屏幕截图 2023-01-31 094911](https://user-images.githubusercontent.com/17617116/215638949-9be15d3a-c68d-487c-850f-acb56613cdf7.png)
但无论修改前还是修改后
`/packages` 下代码都出现`Cannot find module` bug
![image](https://user-images.githubusercontent.com/17617116/215639420-015e50bb-7293-4520-8053-b9255c6c054c.png)

**Reproduction**
no needed

**System Info**
```
System:
    OS:Windows 10 19044.2486
    CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
    Memory:  8.00 GB (7.81 GB 可用)
    
  Binaries:
    Node: v18.12.1
    Yarn: 1.22.19
    npm: 8.19.2
    ts:4.9
```
**Used Package Manager**
pnpm@7.26.0

**Validations**

 - [x] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
 - [x] Read the [Contributing Guide](https://github.com/sxzz/contribute).
 - [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
 - [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
 - [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alexzhang1030** [comment]
customConditions 是 `ts@5` 的新配置，请确保更新到最新依赖了

**Comment by AliceLanniste** [comment]
> customConditions 是 `ts@5` 的新配置，请确保更新到最新依赖了
我更新了还是这样
![image](https://user-images.githubusercontent.com/17617116/215645598-2e4364bc-1560-4b5d-8068-e0fa3fcadbe3.png)

**Comment by alexzhang1030** [comment]
> > customConditions 是 `ts@5` 的新配置，请确保更新到最新依赖了
> > 我更新了还是这样
> > ![image](https://user-images.githubusercontent.com/17617116/215645598-2e4364bc-1560-4b5d-8068-e0fa3fcadbe3.png)

看一下是否开了 `takeover` mode，volar 插件是否是最新，右下角是否显示的是这样：

<img width="291" alt="image" src="https://user-images.githubusercontent.com/49969959/215647697-14900f94-ce9d-4aaf-874a-6149462046bf.png">

最后重新一下 Vue 服务或者 VS Code 如果还出现问题，就执行：

`nr clean && rm -fr **/node_modules && ni && nr build` 然后重新 VS Code，这样肯定是没问题了

**Comment by AliceLanniste** [comment]
> > > customConditions 是 `ts@5` 的新配置，请确保更新到最新依赖了
> > > 我更新了还是这样
> > > ![image](https://user-images.githubusercontent.com/17617116/215645598-2e4364bc-1560-4b5d-8068-e0fa3fcadbe3.png)
> 
> 看一下是否开了 `takeover` mode，volar 插件是否是最新，右下角是否显示的是这样：
> 
> <img alt="image" width="291" src="https://user-images.githubusercontent.com/49969959/215647697-14900f94-ce9d-4aaf-874a-6149462046bf.png">
> 
> 最后重启一下 Vue 服务或者 VS Code 如果还出现问题，就执行：
> 
> `nr clean && rm -fr **/node_modules && ni && nr build` 然后重启 VS Code，这样肯定是没问题了

谢谢我试试

**Comment by sxzz** [comment]
Tips: 如问题已解决，请关闭本 issue

**Comment by AliceLanniste** [comment]
已经解决了谢谢
