### ISSUE TITLE
defineOptions的extends似乎无效

### ISSUE THREAD

**Issue by woodenF** [sxzz/unplugin-vue-macros#259]
### Describe the bug

做组件二次封装的时候，可以在defineComponent里使用extends获得别封装组件的props提示，我在setup语法糖下使用defineOptions的extends没有生效

### Reproduction

defineOptions({   name: 'Hello',   extends: NButton });

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.56 GB / 7.89 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thank you.

https://antfu.me/posts/why-reproductions-are-required-zh

**Comment by woodenF** [comment]
![image](https://user-images.githubusercontent.com/22868812/216290224-4b2a1cf2-63c5-4af8-8d52-cd2ec603a220.png)
当我在defineComponent下使用extends 我要二次封装的组件，在使用时能得到原本组件的类型提示。
![image](https://user-images.githubusercontent.com/22868812/216291091-e60c6415-dec4-45c8-8119-527d1cddcb6a.png)
但我在defineOptions下使用extends，不能获得相同的效果

**Comment by lx11573** [comment]
这个已经可以了吗？现在貌似还是没有任何的提示

**Comment by sxzz** [comment]
Plz configure volar plugin
https://vue-macros.sxzz.moe/macros/define-options.html#volar-configuration

**Comment by lx11573** [comment]
> Plz configure volar plugin https://vue-macros.sxzz.moe/macros/define-options.html#volar-configuration

可以了，感谢
