### ISSUE TITLE
Allow using deep watcher for `defineModel`

### ISSUE THREAD

**Issue by mahdiboomeri** [sxzz/unplugin-vue-macros#267]
### Clear and concise description of the problem

When dealing with nested arrays and objects the watcher doesn't get triggered automatically, consider the following example: 

```vue
// Parent.vue
<Child v-model:data="data" @update:data="someFunction" />

// Child.vue
<script setip>
const { data } = defineModel<{
  data: {
    phone: string;
    name: {
        first: string;
        last: string;
    }
  };
}>();

// The event doesn't get triggered so we have to manually watch the `data`
const emit = defineEmits<{
  (event: 'update'): void;
}>();
watch(data, () => emit('update'), { deep: true });
</script>
```

### Suggested solution

I suggest one of the following approaches: 
- Pass `deep: true` to `useVModel` by default
- Allow passing custom options to `defineModel`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Added usage to the docs, thanks!

<img width="721" alt="image" src="https://user-images.githubusercontent.com/6481596/219389464-0d0555f0-23f8-404c-acc6-e9d99822d78e.png">
