### ISSUE TITLE
使用VueMacros中rollup报错

### ISSUE THREAD

**Issue by Luxii44** [sxzz/unplugin-vue-macros#269]
我在使用VueMacros中的rollup时，要定义一个name属性，我定义后，说显示name属性已经废弃，这个怎么解决
![image](https://user-images.githubusercontent.com/90958941/219253058-329e2980-5faf-4a34-bc25-7f50d07665e8.png)

**Comment by sxzz** [comment]
I don't think it's a bug from Vue Macros, but you can provide a minimum reproduction.

https://antfu.me/posts/why-reproductions-are-required

**Comment by Luxii44** [comment]
> 我在使用VueMacros中的rollup时，要定义一个name属性，我定义后，说显示name属性已经废弃，这个怎么解决 ![image](https://user-images.githubusercontent.com/90958941/219253058-329e2980-5faf-4a34-bc25-7f50d07665e8.png)
