### ISSUE TITLE
Error: Cannot find module '@vue-macros/volar/define-model'

### ISSUE THREAD

**Issue by davy-ikv** [sxzz/unplugin-vue-macros#293]
### Describe the bug

In 1.9.1, `unplugin-vue-macros` doesn't list `@vue-macros/volar` as dependency

https://www.npmjs.com/package/unplugin-vue-macros?activeTab=explore

This cause `@vue-macros/volar` won't be installed by default if package.json only list `unplugin-vue-macros` as dependency, and Volar will complain that it couldn't load volar-related modules while putting this setting in `tsconfig.json`:

```json
"vueCompilerOptions": {
  "plugins": [
    "@vue-macros/volar/define-model"
  ]
}
```

### Reproduction

`npm i -D unplugin-vue-macros` and run Volar in VSCode

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 129.83 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.15.0 - ~/.nodenv/versions/16.15.0/bin/node
    Yarn: 1.22.10 - ~/.bin/yarn
    npm: 8.19.2 - ~/.nodenv/versions/16.15.0/bin/npm
  Browsers:
    Safari: 16.3
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Following [the docs](https://vue-macros.sxzz.moe/guide/bundler-integration.html#volar-support), please install it manually.
