### ISSUE TITLE
Define single prop & emits macro `defineProp` & `defineEmit`

### ISSUE THREAD

**Issue by zzhenryquezz** [sxzz/unplugin-vue-macros#294]
### Clear and concise description of the problem

Hi Friend, thanks for the good lib!

So I was thinking that would be nice to have a way to define single `props and emits`  inside the component.

Today we need to declare all props & emits into a single variable and because of this, we will always have a top section in the component where we will define props and emits that will be linked to all code of our components even when following “Logical Concern” guidelines.

### Suggested solution

So would be nice if we could have a macro to declare a single prop or emit for a variable.

Proposal:
```ts
// Props

const count = defineProp(1) // default value 1

const count = defineProp<number>() // prop type number

// Emits

const updateCount = defineEmit('update:count')

const updateCount = defineEmit<number>('update:count') // emit type arg number

const updateCount= defineEmit('update:count', (value: number) => value < 3)) // validation
```

This way we can eliminate the need to have a top section to declare props & emits and we can organize better the code.

## Example:

Before:

```ts
// Props & emits

const props = defineProps(['product', 'category'])

const emit = defineEmits(['update:product', 'update:category'])

// Products

const selectedProduct = computed({
    get: () => props.product,
    set: (v) => emit('update:product', v)
})

// Categories

const selectedCategory= computed({
    get: () => props.category,
    set: (v) => emit('update:category', v)
})

```

After
```ts
// Products

const product = defineProp('product')

const updateProduct = defineEmit('update:product')

const selectedProduct = computed({
    get: () => product.value,
    set: (v) => updateProduct(v)
})

// Categories

const category = defineProp('category')

const updateCategory = defineEmit('update:category')

const selectedCategory= computed({
    get: () => category.value,
    set: (v) => updateCategory(v)
})


```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Looks good! PR welcome.

**Comment by sxzz** [comment]
Looks good! PR welcome.
