### ISSUE TITLE
Failed to parse source for import analysis when using Histoire

### ISSUE THREAD

**Issue by Hrishikesh-K** [sxzz/unplugin-vue-macros#301]
### Describe the bug

Historie build fails with the error:

```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
```

When simply using `npm run build`, everything works, but due to this issue cannot use Historie. I'm only trying to use `reactivityTransform` and `betterDefine`.

Try running `npm run story:dev` or `nom run story:build` in the provided reproduction.

### Reproduction

https://stackblitz.com/edit/hk-vue-macros-histoire

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 120.51 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AliceLanniste** [comment]
hi, I I tried changing the `t-button.story.vue` and `t-icon.story.vue`  file name.
![屏幕截图 2023-03-19 202740](https://user-images.githubusercontent.com/17617116/226175375-f080f9d3-4fb0-4b3d-a750-e35696431f88.png)
And then running `npm run story:dev` ,it works

**Comment by Hrishikesh-K** [comment]
Thank you for replying. I think it works because Histoire then doesn't load those files as stories. Histoire will only look for: `.story.vue`: https://histoire.dev/reference/config.html#storymatch (by default).

Since the files are not being loaded, Histoire is not parsing them and thus, the problem doesn't occur. As soon as the file is parsed, it throws an error.

**Comment by sxzz** [comment]
You can disable `setupSFC` feature. Because the file ending with `.setup.ts` will be treated with Vue SFC file.

```ts
vueMacros({
  setupSFC: false,
  plugins: {
    vue: vue(),
  },
}),
```

**Comment by Hrishikesh-K** [comment]
Oh that worked! Thanks!
