### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by yuxinyu12345** [sxzz/unplugin-vue-macros#304]
![image](https://user-images.githubusercontent.com/51396023/224648723-41331086-a050-4c54-a876-00f55025862b.png)

This dependency was not found:

* -!../../../node_modules/cache-loader/dist/cjs.js??ref--13-0!../../../node_modules/babel-loader/lib/index.js!../../../node_modules/cache-loader/dist/cjs.js??ref--1-0!../../../node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js??vue-loader-options!../../../node_modules/unplugin/dist/webpack/loaders/transform.js??unplugin-vue-define-options!./index.vue?vue&type=script&lang=js& in ./src/components/uploader/index.vue?vue&type=script&lang=js&

* To install it, you can run: npm install --save -!../../../node_modules/cache-loader/dist/cjs.js??ref--13-0!../../../node_modules/babel-loader/lib/index.js!../../../node_modules/cache-loader/dist/cjs.js??ref--1-0!../../../node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js??vue-loader-options!../../../node_modules/unplugin/dist/webpack/loaders/transform.js??unplugin-vue-define-options!./index.vue?vue&type=script&lang=js&

package version:
unplugin-vue-define-options: 1.2.4
Vue: 2.7.14
@vue/cli-service: 4.5.18

demo address:  https://github.com/yuxinyu12345/demo

**Comment by sxzz** [comment]
Please upgrade your dependency `unplugin`. Unplugin is fixed this issue in v1.3.1
