### ISSUE TITLE
better-define generate the wrong runtime prop type

### ISSUE THREAD

**Issue by ccitsxy** [sxzz/unplugin-vue-macros#307]
### Describe the bug

```
[Vue warn]: Invalid prop: type check failed for prop "content". Expected String with value "[object Object]", got Object  
  at <Item content= Object > 
  at <App>
```

src/components/Item.vue
```
import type { Component } from 'vue';

const props = defineProps<{
  content: string | Component;
}>();
```
The generated runtime prop type
```
const props = defineProps({
  "content": { type: String, required: true,  }
});
```
expected
```
const props = defineProps({
  "content": { type: [String, Object, Function], required: true,  }
});
```

### Reproduction

https://github.com/ccitsxy/vue-macros-prop-type

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 9.36 GB / 15.89 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.41)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wsaca** [comment]
I have a similar problem but using `DefineComponent`, also if I use an interface for example:
```Ts
type Alignment = 'start' | 'center' | 'end' | 'justify';
export interface TextProps {
    content?: string;
    alignment?: Alignment;
}
```
the type resolved for both properties is null instead of `String`.

**Comment by sxzz** [comment]
---


@wsaca Could you please provide more context about your issue? Like with a reproduction repo.

**Comment by sxzz** [comment]
Thanks for your feedback! Fixed and will be released soon.
