### ISSUE TITLE
tsc throw  error TS2307: Cannot find module '@vue-macros/reactivity-transform/vite' or its corresponding type declarations.

### ISSUE THREAD

**Issue by joyexpr** [sxzz/unplugin-vue-macros#309]
### Describe the bug

using  typescript@5.0.2, tsc throw error at  code below,  typescript@4.9.5 is fine

import ReactivityTransform from '@vue-macros/reactivity-transform/vite'

electron.vite.config.ts:21:33 - error TS2307: Cannot find module '@vue-macros/reactivity-transform/vite' or its corresponding type declarations.

### Reproduction

not provided  at the moment

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 18.88 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 86.0
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.1.0 
    vite: ^4.2.0 => 4.2.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
```tsconfig.json
{
  "compilerOptions": {
    "moduleResolution": "bundler"
    // ...
  }
}
```

It's a main feature of TS 5. Please follow the configuration above.
