### ISSUE TITLE
hoist-static will cause inject() can only be used inside setup() or functional components.

### ISSUE THREAD

**Issue by Miofly** [sxzz/unplugin-vue-macros#310]
### Describe the bug

hoist-static -> inject() can only be used inside setup() or functional components.
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/42859910/226075850-797aedec-3b88-438c-bd11-38de7d2a9c16.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/42859910/226075868-d12d1fd5-97d8-47e1-828f-16359e7fadc7.png">

### Reproduction

https://github.com/Miofly/demo-issue-template/tree/vue-macros-issue

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 204.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
`useNamespace()` is not a static value and used `inject()` internally [here](https://github.com/Miofly/demo-issue-template/blob/vue-macros-issue/src/utils.ts#L13), which needs instance context, so it can only run after the component is inited.

The code will be compiled to
```vue
<script lang="ts">
import { useNamespace } from './utils';
const ns = useNamespace('divider');

export default {
	name: ns.b()
};
</script>
```


Read further: https://vuejs.org/api/composition-api-dependency-injection.html#inject
> Similar to lifecycle hook registration APIs, inject() must be called synchronously during a component's setup() phase.
