### ISSUE TITLE
Docs page 404 page layout error

### ISSUE THREAD

**Issue by ryuhangyeong** [sxzz/unplugin-vue-macros#311]
## Link

Occurs when access is made by clicking an external link.

https://vue-macros.sxzz.moe/macros/define-slots.html

## Preview

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/27342882/226163540-fbe1a4ba-3634-49ba-b3b0-3ad2007a4dd2.png">

### Reproduction

https://vue-macros.sxzz.moe/macros/define-slots.html

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 2.14 GB / 7.72 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Vue Macros is using PWA, there could be some bad cache

**Comment by ryuhangyeong** [comment]
@sxzz yes. I found it to be a temporary problem and closed it.
