### ISSUE TITLE
defineOptions Not work when using webpack with Vue3

### ISSUE THREAD

**Issue by kekexunxun** [sxzz/unplugin-vue-macros#327]
https://github.com/sxzz/unplugin-vue-macros/blob/78d57f46348a43cc747b6aa17d8a4344455e8a1f/packages/define-options/src/index.ts#L22

This question is similar to [Unplugin-element-plus](https://github.com/element-plus/unplugin-element-plus/issues/185)
I use @vue/cli-service@5 which means webpack 5
Just add `REGEX_VUE_SUB` to __options.include__ as default can fix this problem, not only Vue2 needs check transformed filename.

**Comment by NMF-Mengfei** [comment]
The same problem occurred when I used vue3 + webpack. 
I followed the documentation specification, but the console still reported defineOptions is not defined，
I would like to know what should be changed.

**Comment by NMF-Mengfei** [comment]
I'm having the same issue with defineOptions is not defined error when using Vue 3 with Webpack, despite following the documentation. I'm wondering what changes I should make to fix it.

**Comment by kekexunxun** [comment]
Only need set options cover default options can solve this problem @NMF-Mengfei

**Comment by kekexunxun** [comment]
setup的内容不会体现在 __.vue__ 文件中，而是在 __.vue?vue&type=script__ ，所以默认的Vue3文件后缀校验应该补充`REGEX_VUE_SUB`

**Comment by sxzz** [comment]
Could you please provide a minimum reproduction? Thanks!

**Comment by kekexunxun** [comment]
@sxzz As I mentioned at the top of issue, there's a simple reproduction. https://stackblitz.com/edit/vitejs-vite-drvu4g?file=src/App.vue
