### ISSUE TITLE
'defineModels' is not defined (eslint)

### ISSUE THREAD

**Issue by BuddhaNag12** [sxzz/unplugin-vue-macros#335]
### Describe the bug

**Getting eslint error while using defineModels**
"vue": "2.7.0"
 "@vue-macros/volar": "^0.9.5",
"unplugin-vue-macros": "^2.0.0",

tsconfig.json
    "vueCompilerOptions": {
        "target": 2.7,
        "plugins": [
            "@vue-macros/volar/define-options",
            "@vue-macros/volar/define-models",
            "@vue-macros/volar/define-props",
            "@vue-macros/volar/define-props-refs",
            "@vue-macros/volar/short-vmodel",
            "@vue-macros/volar/define-slots",
            "@vue-macros/volar/export-props"
        ]
    },

![image](https://user-images.githubusercontent.com/31861172/230938709-d45fd057-f90c-46f0-826a-d86557288fa6.png)

### Reproduction

Basic vue2.7 setup with eslint

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 9.53 GB / 15.48 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/buddh/AppData/Roaming/npm/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
See https://github.com/sxzz/unplugin-vue-macros/issues/171#issuecomment-1333326745
https://github.com/sxzz/unplugin-vue-macros/issues/74#issuecomment-1481001869
