### ISSUE TITLE
can not use useCssVars

### ISSUE THREAD

**Issue by max512060925** [sxzz/unplugin-vue-macros#358]
### Describe the bug

https://github.com/sxzz/unplugin-vue-macros/issues/270
vue-core has fixed
but  I still can not use with @vue-macros/reactivity-transform

```js
let background = ref('red')
```
It's work

```js
let background = $ref('red')
```
It's not work

### Reproduction

https://github.com/sxzz/unplugin-vue-macros/issues/270

### System Info

```Shell
Chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed in [v3.3.0-alpha.6](https://github.com/vuejs/core/releases/tag/v3.3.0-alpha.6). What's your vue version?

**Comment by max512060925** [comment]
v3.2.47 but I can use `ref` in this version，so I need to wait v3.3.0 release？

**Comment by sxzz** [comment]
Yes.
