### ISSUE TITLE
defineOptions中的name可以支持变量吗

### ISSUE THREAD

**Issue by Miofly** [sxzz/unplugin-vue-macros#37]
比如

```
  const myName = 'popup'
  defineOptions({
    name: myName
  });
```

**Comment by sxzz** [comment]
Not supported yet. But I create a PR to vue. https://github.com/vuejs/core/pull/5752

**Comment by sxzz** [comment]
Now you can. Please use plugin `unplugin-vue-macros` and upgrade it to the latest version. `hoistStatic` feature is enabled by default.

**Comment by Miofly** [comment]
```
  const _test = 'wfly';
  const name = `${_test}-app-provider`;

  defineOptions({
    name
  });
```
这种写法是不是不支持

**Comment by sxzz** [comment]
Try
```ts
const _test = 'wfly'
const name = /*hoist-static*/ `${_test}-app-provider`
```

**Comment by Miofly** [comment]
> Try
> 
> ```ts
> const _test = 'wfly'
> const name = /*hoist-static*/ `${_test}-app-provider`
> ```

可以了实现了我想要的功能，谢谢大佬
const [name, bem] = /* hoist-static*/ createNamespace('config-provider');

**Comment by Miofly** [comment]
如图所示代码， rootMenuEmitter.on 中的 name 是参数，但是这样写会和  /* hoist-static*/ 中的 name 冲突导致崩溃，我现在将函数中的 name 参数重命名为(_name)去解决这个问题，但这个问题是否可以从插件层面去解决呢
<img width="811" alt="image" src="https://user-images.githubusercontent.com/42859910/187205974-24462a7e-00a3-4e5a-828a-e89ee1aef98b.png">

**Comment by sxzz** [comment]
Can't reproduce, please provide a minimum reproduction repo.

**Comment by Miofly** [comment]
> Can't reproduce, please provide a minimum reproduction repo.

https://github.com/Miofly/vite-dev-tree-shaking

**Comment by sxzz** [comment]
try `v0.11.1`

**Comment by Miofly** [comment]
> try `v0.11.1`

it`s correct
