### ISSUE TITLE
找不到名称“defineOptions”，已经设置了types和config ，还是会提示

### ISSUE THREAD

**Issue by qinjo** [sxzz/unplugin-vue-macros#43]
### Describe the bug

![image](https://user-images.githubusercontent.com/60745301/182118384-9454f709-4e5e-4680-9614-0c7a6378d966.png)
![image](https://user-images.githubusercontent.com/60745301/182118545-888e4547-d667-48ea-8caf-9ed32d73be57.png)
![image](https://user-images.githubusercontent.com/60745301/182118572-6f7ef70e-f321-491c-9229-073748231fe9.png)
如上图所示，一直在vue文件中显示找不到名称，试过删掉依赖重现安装，还是会提示

### Reproduction

defineOptions

### System Info

```Shell
macOS
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh

**Comment by sxzz** [comment]
暂时关闭本 issue，请提供复现仓库后打开。
