### ISSUE TITLE
按照文档基本示例运行发生错误

### ISSUE THREAD

**Issue by Ryongyon** [sxzz/unplugin-vue-macros#44]
### Describe the bug

按照文档基本示例提供的代码运行错误：

```javascript
<script setup lang="ts">
import { useSlots } from 'vue'
defineOptions({
  name: 'Foo',
  inheritAttrs: false,
  props: {
    msg: { type: String, default: 'bar' },
  },
  emits: ['change', 'update'],
})
const slots = useSlots()
</script>
```

报错信息：

```shell
[vite] Internal server error: unplugin-vue-define-options SyntaxError: defineOptions() please use defineProps or defineEmits instead.
```

搜索 issuse 发现一条相关的问题：[https://github.com/sxzz/unplugin-vue-macros/issues/19](https://github.com/sxzz/unplugin-vue-macros/issues/19 "https://github.com/sxzz/unplugin-vue-macros/issues/19")

但不能够消除我的困惑，根据作者提供的错误示例模板来看，我以为指的是 `defineOptions` 不能够与 `defineProps` 同时进行使用。

之后我创建了一个 Vite + Vue3 模板，按照文档中的基本示例提供的代码运行时也发生相同的错误。

所以我不明白这是属于一个 Bug 还是文档有误 或者 解释的不够清楚？如果这不属于一个 Bug 的话希望作者能重新编辑一下文档。

### Reproduction

none

### System Info

```Shell
System:
  OS: Windows 10 10.0.25163
  CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Memory: 16.64 GB / 31.94 GB
Binaries:
  Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
  npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.25163.1010.0), Chromium (98.0.1108.50)
  Internet Explorer: 11.0.25163.1000
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
噢，我忘了改 README 中的示例，我稍后会修复它。
Oh, I forget to update the example in the readme, I will fix it later.

`defineOptions` 不能用来定义 `props`，因为 `defineProps` 是专门用来定义 props 的，用 `defineOptions` 来定义 props 并没有什么好处。

`defineOptions` can't be used for defining `props`, because `defineProps` is designed for only one function - defining the props. There's no benefit for defining props using `defineOptions`.

**Comment by Ryongyon** [comment]
如果有可能实现的话更希望 defineOptions 函数能够定义 props、emits 这些，那就更棒了，这样就不用再单独去定义其他宏函数。代码能够简洁、集中很多。不然的话 defineOptions 的作用似乎就没有那么大了。但是或许是底层代码不允许那么去做？十分感谢作者能够抽空回复这个 issuse，感谢！

**Comment by sxzz** [comment]
目前是有意为之的，后续可能会进一步在 RFC 中讨论允许这种写法。

This is currently intentional and may be discussed further in the RFC to allow this writing style.
