### ISSUE TITLE
定义丢失

### ISSUE THREAD

**Issue by ModyQyW** [sxzz/unplugin-vue-macros#46]
### Describe the bug

根据 README 配置了 `unplugin-vue-macros`，没有找到 `defineOptions` 的定义。如果是 `unplugin-vue-define-options` 则没有这个问题。

<img width="401" alt="image" src="https://user-images.githubusercontent.com/31850793/182611479-fb3bb318-2f6c-4296-be61-11c584c92603.png">

如果 `tsconfig.json` 里的 `types` 调整一下，则正常。

```json
{
  "compilerOptions": {
    ...,
    "types": ["unplugin-vue-macros/macros-global"]
  },
  ...
}

```

### Reproduction

https://github.com/ModyQyW/unplugin-vue-macros-bug

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 43.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
文档有误，已修改
