### ISSUE TITLE
发包版本问题

### ISSUE THREAD

**Issue by ModyQyW** [sxzz/unplugin-vue-macros#47]
### Describe the bug

`unplugin-vue-macros@0.7.2` 依赖于 `unplugin-vue-define-options@0.7.2`，但 `unplugin-vue-define-options@0.7.2` 并没有发布到 npm 上。

<https://cdn.jsdelivr.net/npm/unplugin-vue-macros@0.7.2/package.json>
<img width="662" alt="image" src="https://user-images.githubusercontent.com/31850793/182738203-b6c3e3d9-02d3-4715-9984-48fa0a7fe975.png">

<https://www.npmjs.com/package/unplugin-vue-define-options>
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/31850793/182738221-031c24aa-7a39-4a16-914a-7c420e77770a.png">

### Reproduction

None

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 46.07 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed, please try the latest version.
