### ISSUE TITLE
Vite: Module has no default export.

### ISSUE THREAD

**Issue by victor-one** [sxzz/unplugin-vue-macros#48]
当在组件中引入使用了defineOptions的模块时报错：
![screenshot-20220807-202035](https://user-images.githubusercontent.com/70365350/183290678-4b25614f-6c12-4686-895d-413d5f8f4d26.png)
![screenshot-20220807-202058](https://user-images.githubusercontent.com/70365350/183290680-a9c838a2-6fa1-42ee-9d98-ca882769fd0f.png)
vite的配置如下：
![screenshot-20220807-203442](https://user-images.githubusercontent.com/70365350/183290764-0037b6cb-77a5-4235-8138-79af6729485c.png)

**Comment by sxzz** [comment]
确保是 <script setup> 块中。或附带最小复现仓库。

**Comment by victor-one** [comment]
在`<script setup>`块中，附上对应模块代码demo如下：
```vue
<template>
  DataSource
</template>

<script setup lang="ts">
  import { DataBoard } from '@element-plus/icons-vue';

  defineOptions({
    label: '数据源',
    order: 2,
    icon: DataBoard,
  })
</script>
```

**Comment by sxzz** [comment]
无法复现，需要提供一个实际的例子。GitHub repo 或 [stackblitz](https://stackblitz.com/).

**Comment by victor-one** [comment]
已解决，Vetur禁用后，不再报错，十分感谢您的帮助，愿您有一个美好的夜晚。

![0C150D1B](https://user-images.githubusercontent.com/70365350/183300639-f0f7a618-6acf-4bb9-8b06-6608c9173507.jpg)
