### ISSUE TITLE
defineModel不会生成相应的d.ts,vscode无代码提示

### ISSUE THREAD

**Issue by xiankaiqun** [sxzz/unplugin-vue-macros#51]
### Describe the bug

```
 let { visible } = defineModel<{
    visible?: boolean;
  }>();
```

<img width="572" alt="image" src="https://user-images.githubusercontent.com/26294948/184478047-fdabb8a0-41f7-43b0-b564-bb1a10f5cc2e.png">

```
 const props = defineProps<{
    visible?: boolean;
  }>();

  const emit = defineEmits<{
    (event: 'update:visible', data?: boolean): void;
  }>();
```
<img width="905" alt="image" src="https://user-images.githubusercontent.com/26294948/184478252-57db9546-49d9-463f-ba3d-f8b6bd0ad6c9.png">

### Reproduction

none

### System Info

```Shell
System:
    OS: macOS 12.4
    Memory: 441.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Yeah, it hasn't been implemented yet.

**Comment by sxzz** [comment]
Waiting Volar plugin API to be more powerful...
