### ISSUE TITLE
defineModel can't resolve inline expression, addition assignment and increment in function

### ISSUE THREAD

**Issue by LoTwT** [sxzz/unplugin-vue-macros#55]
### Describe the bug

defineModel can't resolve inline expression, addition assignment and increment in function

```bash
- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Package Manager:  `pnpm@7.9.0`
- unplugin-vue-macros version: `0.10.0`
```

It seems I can't write `vite.config.ts` in the stackblitz reproduction, so it may need to be copied from `HelloWorld.vue` and `App.vue`. 

### Reproduction

https://stackblitz.com/edit/vue-w5pssk?file=src/components/HelloWorld.vue

### System Info

```Shell
it's ok in the terminal.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Will fix soon. 😇

**Comment by sxzz** [comment]
> **Warning**: Assignment expression is only supported in `<script setup>` block. In other words invalid in `<template>`.

> **Warning**: 赋值表达式仅在 `<script setup>` 块中有效，换言之在 `<template>` 中无效。
