### ISSUE TITLE
unplugin-vue-define-options esbuild  Cannot read properties of undefined

### ISSUE THREAD

**Issue by nextjm** [sxzz/unplugin-vue-macros#56]
### Describe the bug

![image](https://user-images.githubusercontent.com/19681693/185391531-76f6ad82-7374-461b-8eb8-9642a1f9f07a.png)
![image](https://user-images.githubusercontent.com/19681693/185391566-07bc2741-ecb1-4219-8156-81e876d584d4.png)
		"esbuild": "^0.13.15",
                "unplugin": "^0.9.2",
		"unplugin-vue": "^0.2.2",
		"unplugin-vue-define-options": "^0.10.0",

### Reproduction

[cant](https://github.com/nextjm/unplugin-vue-define-options-esbuild-demo)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 4.39 GB / 15.86 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54), ChromiumDev (Hey friend
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
please provide reproduction repo
https://antfu.me/posts/why-reproductions-are-required-zh

**Comment by nextjm** [comment]
reproduction https://github.com/nextjm/unplugin-vue-define-options-esbuild-demo  @sxzz

**Comment by sxzz** [comment]
@nextjm Please upgrade your esbuild to the latest version.

By the way, you still need [esbuild-plugin-transform](https://github.com/sxzz/esbuild-plugin-transform), since there's no transform stage in esbuild https://github.com/evanw/esbuild/issues/1902

```ts
import { Transform } from 'esbuild-plugin-transform'
// ...
    plugins: [
      Transform({
        plugins: [
          DefineOptions(),
          vue({
            sourceMap: false,
            style: {
              preprocessLang: 'less',
              preprocessOptions: {
                less: {
                  javascriptEnabled: true,
                  additionalData: `@import '${process.cwd()}/packages/styles/index.less'`,
                },
              },
            },
          }),
        ],
      }),
    ],
```
