### ISSUE TITLE
在js项目中 无法通过eslint no-undef 校验

### ISSUE THREAD

**Issue by Lupeiwen0** [sxzz/unplugin-vue-macros#61]
### Describe the bug

   'defineOptions' is not defined eslint no-undef
   
   可以使用 vite 快速构建一个js项目，开启eslint 
   
   使用 defineOptions 便会出现这个错误提示

### Reproduction

npm create vite@latest

### System Info

```Shell
MacOs Vscode
```

### Used Package Manager

npm

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
自行配置 ESLint 规则
```json
{
  globals: {
    defineOptions: 'readonly'
  }
}
```
