### ISSUE TITLE
webstorm中无代码提示

### ISSUE THREAD

**Issue by tongxin-77** [sxzz/unplugin-vue-macros#62]
### Clear and concise description of the problem

//index.vue
defineOptions({
  name: "ColorSelector"
})

在其他组件中使用时无代码提示
![image](https://user-images.githubusercontent.com/58261510/188077725-7f2a5526-a7ce-44b3-8b0f-df88fd3b1f57.png)

### Suggested solution

期望值
![image](https://user-images.githubusercontent.com/58261510/188078034-8d3e1230-fc89-44b4-ac6d-3d1fb0ae8abe.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
VSCode and Volar are recommended. volar is the first support for Vue.
建议使用 VSCode 和 Volar。Volar 是 Vue 的第一支持。

**Comment by sxzz** [comment]
Webstorm has no support plans at this time.
Webstorm 暂无支持计划。
