### ISSUE TITLE
defineRender 在某些情况下程序会直接崩溃

### ISSUE THREAD

**Issue by Miofly** [sxzz/unplugin-vue-macros#63]
### Describe the bug

首先 引入了 CSSProperties 后，如果不加 template 模板出现如下报错，当然不限于这个属性。还有不支持热更新
<img width="570" alt="image" src="https://user-images.githubusercontent.com/42859910/188269382-b7203354-5e63-4137-8d23-f4a64970daf1.png">

```
<script lang="tsx" setup>
  import { CSSProperties } from 'vue';

  interface Props {
    test?: any;
  }

  const { test = '11' } = defineProps<Props>();

  defineRender(() => {
    return (
      <div>
        <h1>{test}</h1>
      </div>
    );
  });
</script>

<template>

</template>
```

### Reproduction

如上述代码

### System Info

```Shell
MacOs Webstrom

 "vite": "3.0.9",
"unplugin-vue-macros": "^0.11.1",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
尝试
```diff
--- import { CSSProperties } from 'vue';
+++ import type { CSSProperties } from 'vue';
```

**Comment by sxzz** [comment]
Can't reproduce. Please provide a reproduction repo.
无法复现。请提供复现仓库。
