### ISSUE TITLE
 reading  @vue/compiler-sfc@2.7.10 parse result.descriptor error

### ISSUE THREAD

**Issue by colinzxz** [sxzz/unplugin-vue-macros#66]
### Describe the bug

Error info: 
`unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'script')`

### Reproduction

https://codesandbox.io/s/vue2-define-options-253lv4

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/_8/56jw43kd3736fw5wjm2hjj_m0000gn/T/fnm_multishells/5286_1662459564218/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.5.0 - /var/folders/_8/56jw43kd3736fw5wjm2hjj_m0000gn/T/fnm_multishells/5286_1662459564218/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 100.0
    Safari: 15.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed, released as `v0.11.2`
