### ISSUE TITLE
Feature Request: How about transform Object jsx component to Functional Component?

### ISSUE THREAD

**Issue by SnowingFox** [sxzz/unplugin-vue-macros#70]
### Clear and concise description of the problem

i think `setupSFC`, `defineRender` is a nice vue-jsx trial. But obviously they have serveral limitations, by using your playground example, i tried to use `functional component code style` to organize my code, but it compiled failed.

`foo.setup.tsx`
```tsx
function A() {
  return (
    <div>1</div>
  )
}

export default () => (
  <div>
    <A />
    <h1>Hello World</h1>
  </div>
)
```

it will compiled to
```tsx
<script setup lang="tsx">function A() {
  return (
    <div>1</div>
  )
}


defineRender(() => (
  <div>
    <A />
    <h1>Hello World</h1>
  </div>
));</script>
```

this makes me a little sad, because the code is correct jsx style, why plugin can't make it run? so i think that's your plugin limitation, i guess you want to make vue component close to `functional component` (just a guess), so why not change mind?

### Suggested solution

we can use compiler to implement it.

for example

```tsx
const App: SetupFC<{
    count: number
}> = (props) => {
    const count = ref(props.count)
    
    return () => (
        <div>
            <p>{ref.value}<p>
            <button onClick={() => count.value++}>inc</button>
        </div>
    )
}
```

it will compiled to

```tsx
const App = defineSetupComponent(() => {
    const props = defineProps<{
        count: number
    }>()
    
    const count = ref(props.count)
    
    return () => (
        <div>
            <p>{ref.value}<p>
            <button onClick={() => count.value++}>inc</button>
        </div>
    )
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
I'm a little bit confused. If you wanna put two or more components in one file, then you could use [`setupComponent`](https://github.com/sxzz/unplugin-vue-macros#setupcomponent-%EF%B8%8F-experimental) feature. setup**SFC** means you can only put ONE component on ONE file.

**Comment by sxzz** [comment]
As you mentioned in `Suggested solution`, I think the idea is pretty cool. I will consider it.

**Comment by sxzz** [comment]
@SnowingFox I sent a message to for via Discord. Could we discuss this more detailed on it?

**Comment by sxzz** [comment]
Added in d235078ecd5ee3d0837fb426120d8c9a36d2b5cb
