### ISSUE TITLE
After the secondary plug-in is configured, does the webpack not translate the defineOptions, or does it refer to the previous one?

### ISSUE THREAD

**Issue by yuArimer** [sxzz/unplugin-vue-macros#72]
### Describe the bug

 webpack.config.js中的配置
 plugins: [
    new ProgressBarPlugin(),
    new VueLoaderPlugin(),
    require('unplugin-vue-define-options/webpack')()
  ],
未打包之前的页面defineOptions
import { ElInput } from 'element-plus';

defineOptions({
  name: 'SyInputNumber',
});

### Reproduction

product

### System Info

```Shell
打包之后的
setup(__props, { emit }) {
        const props = __props;
        defineOptions({
            name: 'SyInputNumber',
        });
        /* emit */
        /* 全局禁用 */
        let inputDisabled = (0,external_vue_namespaceObject.computed)(() => props.disabled);
        /* 根据步长、精准度处理数值 */
        let numPrecision = (0,external_vue_namespaceObject.computed)(() => {
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh
