### ISSUE TITLE
'defineOptions' is not defined.

### ISSUE THREAD

**Issue by yangliguo7** [sxzz/unplugin-vue-macros#74]
### Describe the bug

First of all . thanks for code

Probably a mistake because I missed something, I'm sorry for that 

![image](https://user-images.githubusercontent.com/46318880/193055434-629dbc13-1f5e-4a2b-9c4f-2c0f3c91b03f.png)

I use this plugin as described in the README
1、npm i unplugin-vue-define-options -D
2、config vite.config.js
```
import DefineOptions from 'unplugin-vue-define-options/vite'
import Vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [Vue(), DefineOptions()],
})
```
3、config tsconfig.json
```
{
  "compilerOptions": {
    // ...
    "types": ["unplugin-vue-define-options/macros-global" /* ... */]
  }
}
```

Then `vscode` will prompt me `'defineOptions' is not defined.`

the  `defineOptions` does not exist in `.eslintrc-auto-import.json` `auto-imports.d.ts`

### Reproduction

https://github.com/yangliguo7/vite-project

### System Info

```Shell
npm run dev
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
This will is caused by eslint, please disable `no-undef` in TS file. You can refer to

https://github.com/sxzz/eslint-config/blob/main/packages/typescript/index.js#L12-L17

**Comment by yangliguo7** [comment]
Is there only one way to solve this problem? But sometimes I do need eslint to validate my variables.

Why does `defineOptions ` not appear in autoimport.ts file

**Comment by sxzz** [comment]
TS will take over variables checked by ESLint.

Or you can refer to

https://github.com/sxzz/eslint-config/blob/main/packages/vue/index.js#L10-L19

**Comment by yangliguo7** [comment]
I'm sorry to bother you . I set it up as you said .  but when i build the project by vite .

it prompts me `Cannot find name 'defineOptions'.`  what am i missing ?

the vite.config.js
```
export default defineConfig({
  plugins: [
    vue(),
    AutoImport({
      dts: true,
      resolvers: [ElementPlusResolver()],
      imports: ["vue"],
    }),
    Components({
      resolvers: [ElementPlusResolver()],
    }),
    VueDefineOptions(),
  ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
});
```

the  eslint
```
module.exports = {
  globals: {
    defineOptions: "readonly",
  }....
```

**Comment by sxzz** [comment]
Check your tsconfig file
https://github.com/sxzz/unplugin-vue-macros/tree/main/packages/define-options#typescript-support

**Comment by sxzz** [comment]
Can't open

**Comment by yangliguo7** [comment]
Im sorry.  try it again .  Just had a problem with the network

**Comment by sxzz** [comment]
Can't reproduce. Do you use VSCode?

**Comment by yangliguo7** [comment]
yep.  I delete package-lock.json and  reinstall dependencies.   but It  aslo doesn't work.
```
vite v3.1.7 building for production...
transforming (1349) node_modules\lodash-es\_isKeyable.jssrc/components/table/src/table.vue:19:1 - error TS2304: Cannot find name 'defineOptions'.

19 defineOptions({
   ~~~~~~~~~~~~~

src/components/form/src/form.vue:32:1 - error TS2304: Cannot find name 'defineOptions'.

32 defineOptions({
   ~~~~~~~~~~~~~

src/components/table/src/tableColumn.vue:51:1 - error TS2304: Cannot find name 'defineOptions'.

51 defineOptions({
   ~~~~~~~~~~~~~
```

**Comment by yangliguo7** [comment]
could you delete lock.json . and reinstall  it again 
.
`cloudartifact.ipd.hihonor.com` is  our company's private register . Im sorry for that

**Comment by sxzz** [comment]
😅 You didn't add types to `tsconfig.vitest.json`. Just change it to `tsconfig.app.json`.

**Comment by yangliguo7** [comment]
ooooops....... . I am too careless  . I'm sorry for wasting your time. I appreciate your help .

**Comment by matthew-dean** [comment]
I don't understand this answer. ESLint works perfectly fine for Vue 3's built-in macros. Why can't this project do the same thing?

**Comment by sxzz** [comment]
Sorry, but no. Because Vue Macros don't really need a very detailed config. Also, `no-undef` is disabled in my projects, since it's useless for a TS project.
