### ISSUE TITLE
Cannot resolve import statements when use `SetupFC` `defineSetupComponent`

### ISSUE THREAD

**Issue by SnowingFox** [sxzz/unplugin-vue-macros#75]
### Describe the bug

for example, we have a component which use `SetupFC` to decorate
```tsx
import { ref } from 'vue'

export const SetupFCType: SetupFC = () => {
  const count = ref(0)

  return () => (
    <div>
      <h3>SetupFCType</h3>
      <p>count: {count.value}</p>
      <button onClick={() => count.value++}>inc & check sourcemap</button>
    </div>
  )
}
```

we hope it can correcly run, but failed, because plugin don't resolve import statements.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-cmxhpm?file=vite.config.ts,src%2FApp.vue,src%2FFoo.tsx,tsconfig.json,package.json&terminal=dev

### System Info

```Shell
System:                                                      
    OS: Windows 10 10.0.19044                                  
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 789.61 MB / 15.79 GB                               
  Binaries:                                                    
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE            
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD             
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD              
  Browsers:                                                    
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)  
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed via #76
