### ISSUE TITLE
Add Tabs for Docs

### ISSUE THREAD

**Issue by sxzz** [sxzz/unplugin-vue-macros#94]
Like [Tauri](https://tauri.app/v1/guides/getting-started/setup/vite#create-the-frontend)

<img width="303" alt="image" src="https://user-images.githubusercontent.com/6481596/195598092-d749e3ec-95fe-4743-be3b-87633f11dd27.png">

I think we could combine bundlers and package managers into multi tabs

- https://vue-macros.sxzz.moe/guide/getting-started#installation
- https://vue-macros.sxzz.moe/guide/getting-started#vite-first-class-support
- https://vue-macros.sxzz.moe/macros/short-vmodel#vite-integration

/cc @alexzhang1030 Would you like to make it?

**Comment by alexzhang1030** [comment]
yep, i will try to implement it

**Comment by alexzhang1030** [comment]
I found a related PR in Vitepress: https://github.com/vuejs/vitepress/pull/1242, sadly it have't merge into main branch yet.

Also I found a implement, see this issue: https://github.com/vuejs/vitepress/pull/1242.

Now we have two choices:

- Waiting for offical support
- Implement it by components

What do you think ? @sxzz

**Comment by alexzhang1030** [comment]
> I think we can use the components for now, then if the PR is merged to vitepress, then we can consider using the official version.

So do I
